version: '3.0'
services:
  dl:
    stdin_open: true  # docker run -i
    tty: true        # docker run -t
    user: root
    # change command + overlay2 storage drive (experimental, remove if failed)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    build:
      context: ./
      dockerfile: ./docker-common/DOCKERFILE
    working_dir: /root/projects
    container_name: dl-train
    # running in privileged
    privileged: true
    devices:
      - /dev/fuse
    environment:
      - FUSE_DEBUG=1
    volumes: 
      - /c/Users/Mo/Documents/GitHub/Projects:/root/projects
      - /var/run/docker.sock:/var/run/docker.sock
      - /c/Users/Mo/.ssh/:/root/.ssh/:ro
      - /c/Users/Mo/.aws/:/root/.aws/:ro
volumes:
  projects:
  docker:
  ssh:
  aws: