version: '3.0'
services:
  dl:
    logging:
      driver: json-file
    stdin_open: true  # docker run -i
    tty: true        # docker run -t
    user: root
    privileged: true
    # Allow container to access host port on gateway IP
    extra_hosts:
      - "host.docker.internal:host-gateway"
      # add kubernetes host:
      - "kubernetes.docker.internal:host-gateway"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          cpus: '1'
          memory: 50G
    build:
      context: ./
      dockerfile: ./docker-common/DOCKERFILE
    # port forward needed when NOT in HOST network 
    # ports:
    #   - "8888:8888" 
    working_dir: /root/projects
    container_name: torch2-train
    # running in privileged
    devices:
      - /dev/fuse
    environment:
      - FUSE_DEBUG=1
    volumes: 
      # May add`delegated` flag to support intensive I/O operations in environ
        # e.g. /c/Users/Mo/Documents/GitHub/Projects:/root/projects:delegated
      - /c/Users/Mo/Documents/GitHub/Projects:/root/projects
      - /var/run/docker.sock:/var/run/docker.sock
      - /c/Users/Mo/.ssh/:/root/.ssh/
      - /c/Users/Mo/.aws/:/root/.aws/
      # Kubernetes configuration
      - /c/Users/Mo/.kube:/root/.kube/
volumes:
  projects:
  docker:
  ssh:
  aws: