FROM supermomo668/dev:aws-pytorch-training_2.0.1-cpu-py310-ubuntu20.04-ec2 as base
 
RUN pip install jupyterlab 
RUN apt update && apt install -y curl tmux

FROM base as builder

# install deps 
COPY environment.yml requirements.txt ./
RUN conda env create -f environment.yml && echo "conda activate dl" > ~/.bashrc 
RUN apt update && apt install nodejs npm ffmpeg libsm6 libxext6 graphviz protobuf-compiler -y && apt autoremove -y 
SHELL ["conda", "run", "-n", "dl", "/bin/bash", "-c"]
RUN pip install -r requirements.txt


FROM builder as runner 

ENV TINI_VERSION v0.6.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/bin/tini
RUN chmod +x /usr/bin/tini
ENTRYPOINT ["/usr/bin/tini", "--"]

SHELL ["/bin/bash", "-c"]
# RUN jupyter-lab --port 8888 --no-browser --ip 0.0.0.0
COPY start_jupyter.sh .
RUN	echo "jupyter-lab --port 8888 --no-browser --ip 0.0.0.0 &!" > 'start_jupyter.sh'
CMD ["bash", "start_jupyter.sh"]

